reread:
  threshold: 0.6

bunch:
  max_gap: 200
  min_gap: 10

ai_api:
  path: "http://localhost:81/v1/vision/detection"
  confidence: 0.35
  recheck_confidence: 0.35

trigger:
  single_frame: 0.85

time_analysis:
  algo: 0
  length: 6

algo0:
  max_jump: 1000

algo1:
  min_move_gap: 15
  close_enough_gap: 30
  prev_frame_weight: 0.4

crop:
  size: 20
