bunch:
  max_gap: 200
  min_gap: 10

ai_api:
  path: "http://localhost:81/v1/vision/detection"
  confidence: 0.2
  recheck_confidence: 0.2

trigger:
  single_frame: 0.85

time_analysis:
  algo: 1
  length: 10

algo0:
  max_jump: 1000

algo1:
  min_move_gap: 15
  prev_frame_weight: 0.4

